# Generated by Django 5.0.7 on 2024-09-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site", models.CharField(max_length=255)),
                ("job_url", models.URLField(unique=True)),
                ("job_url_direct", models.URLField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("job_type", models.CharField(blank=True, max_length=100, null=True)),
                ("date_posted", models.DateTimeField()),
                (
                    "salary_source",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("interval", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=50, null=True)),
                ("is_remote", models.BooleanField(default=False)),
                ("job_level", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "job_function",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_industry",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "listing_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("emails", models.EmailField(blank=True, max_length=254, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("company_url", models.URLField(blank=True, null=True)),
                ("company_url_direct", models.URLField(blank=True, null=True)),
                ("company_addresses", models.TextField(blank=True, null=True)),
                (
                    "company_num_employees",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_revenue",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("company_description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
